_dashboard:
    path:     /
    defaults: { _controller: IntechnologyBackendManagementBundle:Default:index }

_companies:
    path: /companies
    defaults: { _controller: IntechnologyBackendManagementBundle:Company:index }

_company_create:
    path: /company
    defaults: { _controller: IntechnologyBackendManagementBundle:Company:create }

_company_update:
    path: /company/{id}
    defaults: { _controller: IntechnologyBackendManagementBundle:Company:update }

_deployments:
    path: /deployments
    defaults: { _controller: IntechnologyBackendManagementBundle:Deployment:index }

_deployment_create:
    path: /deployment
    defaults: { _controller: IntechnologyBackendManagementBundle:Deployment:create }

_deployment_update:
    path: /deployment/{id}
    defaults: { _controller: IntechnologyBackendManagementBundle:Deployment:update }

_users:
    path: /users
    defaults: { _controller: IntechnologyBackendManagementBundle:User:index }

_user_create:
    path: /user
    defaults: { _controller: IntechnologyBackendManagementBundle:User:create }

_user_update:
    path: /user/{id}
    defaults: { _controller: IntechnologyBackendManagementBundle:User:update }

login_route:
    path:     /login
    defaults: { _controller: IntechnologyBackendManagementBundle:Security:login }

login_check:
    path: /login_check

_logout:
    path: /logout
    #defaults: { _controller: IntechnologyBackendManagementBundle:Security:logout }