# AppBundle/Resources/config/validation.yml
Intechnology\BackendManagementBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        username:
            - NotBlank: ~
        company:
            - NotBlank: ~

Intechnology\BackendManagementBundle\Entity\Company:
    properties:
        name:
            - NotBlank: ~