# AppBundle/Resources/config/validation.yml
Intechnology\BackendManagementBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        username:
            - NotBlank: ~
        company:
            - NotBlank: ~

Intechnology\BackendManagementBundle\Entity\Company:
    properties:
        name:
            - NotBlank: ~
        town:
            - NotBlank: ~
        postcode:
            - NotBlank: ~
        primaryContactName:
            - NotBlank: ~
        primaryContactEmailAddress:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: false