Intechnology\BackendManagementBundle\Entity\HardwareItem:
    type: entity
    table: hardware_item
    indexes:
        status:
            columns:
                - active
                - deleted
        hardware_item_ibfk_1:
            columns:
                - f_deployment_id
        hardware_item_ibfk_2:
            columns:
                - f_parent_hardware_group_id
        hardware_item_ibfk_3:
            columns:
                - f_parent_hardware_item_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hardwareType:
            type: string
            nullable: false
            length: null
            fixed: false
            column: hardware_type
        created:
            type: datetime
            nullable: false
        label:
            type: string
            nullable: false
            length: 100
            fixed: false
        address:
            type: string
            nullable: false
            length: 20
            fixed: false
        active:
            type: string
            nullable: true
            length: null
            fixed: false
            default: Y
        deleted:
            type: string
            nullable: true
            length: null
            fixed: false
            default: N
    manyToOne:
        fDeployment:
            targetEntity: Deployment
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                f_deployment_id:
                    referencedColumnName: id
            orphanRemoval: false
        fParentHardwareGroup:
            targetEntity: HardwareGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                f_parent_hardware_group_id:
                    referencedColumnName: id
            orphanRemoval: false
        fParentHardwareItem:
            targetEntity: HardwareItem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                f_parent_hardware_item_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
