Intechnology\BackendManagementBundle\Entity\HardwareGroup:
    type: entity
    table: hardware_group
    indexes:
        active:
            columns:
                - active
                - deleted
        deployment_id_fk:
            columns:
                - deployment_id
        parent_hardware_group_id_fk:
            columns:
                - parent_hardware_group_id
        parent_hardware_item_id_fk:
            columns:
                - parent_hardware_item_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            fixed: false
        location:
            type: text
            nullable: true
            length: 65535
            fixed: false
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        parentHardwareItem:
            targetEntity: HardwareItem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_hardware_item_id:
                    referencedColumnName: id
            orphanRemoval: false
        deployment:
            targetEntity: Deployment
            cascade: {  }
            mappedBy: hardwareGroups
            inversedBy: hardwareGroups
            joinColumns:
                deployment_id:
                    referencedColumnName: id
            orphanRemoval: false
        parentHardwareGroup:
            targetEntity: HardwareGroup
            cascade: {  }
            mappedBy: hardwareGroup
            inversedBy: null
            joinColumns:
                parent_hardware_group_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
