Intechnology\BackendManagementBundle\Entity\User:
    type: entity
    table: user
    indexes:
        email_address:
            columns:
                - username
                - password
                - is_active
                - deleted
        company_id_fk:
            columns:
                - company_id
        user_type_id_fk:
            columns:
                - user_type_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: last_name
        username:
            type: string
            nullable: true
            length: 50
            fixed: false
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
        telephone:
            type: string
            nullable: true
            length: 20
            fixed: false
        mobileTelephone:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: mobile_telephone
        created:
            type: datetime
            nullable: true
        lastUpdate:
            type: datetime
            nullable: true
            column: last_update
        isActive:
            type: boolean
            nullable: true
            column: is_active
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        company:
            targetEntity: Company
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        userType:
            targetEntity: UserType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preFlush: [setUpdatedValue]
